/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
	Sum := 0
	for x, y := 0, 1; x <= 4000000; x, y = y, x+y {
		if x%2 == 0 {
			fmt.Println(x, "x is even, adding to sum")
			Sum += x
		}
	}
	fmt.Println("Finished, total sum =", Sum)
}